services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      MEMCACHED_URL: ${MEMCACHED_URL}
      PORT: ${PORT}
    networks:
      - backend

networks:
  backend:
    external: true
